export default {
    CHANGE_NEWS_LIST: "CHANGE_NEWS_LIST",
    CHANGE_COMMUNITY_LIST:"CHANGE_COMMUNITY_LIST",
    CHANGE_CONTENT_LIST:"CHANGE_CONTENT_LIST",
    CHANGE_IS_LOADING:"CHANGE_IS_LOADING",
    CHANGE_MASTER_LIST:"CHANGE_MASTER_LIST"
}